kite_expert/kite_expert/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path  # re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from kite_expert import settings

# drf_yasg
schema_view = get_schema_view(
    openapi.Info(
        title=f"{settings.DOMAIN} API",
        default_version="v1",
        description="",
        terms_of_service="",
        contact=openapi.Contact(email=""),
        license=openapi.License(name=""),
    ),
    url=settings.URL,
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("kites.urls", "kites"), namespace="kites")),
    path("api/", include("kites.APIurls")),
    path("__debug__/", include("debug_toolbar.urls")),
    # drf_yasg
    path(
        "docs/swagger<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "docs/swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "docs/redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # re_path(
    #     r"^swagger(?P<format>\.json|\.yaml)$",
    #     schema_view.without_ui(cache_timeout=0),
    #     name="schema-json",
    # ),
    # re_path(
    #     r"^swagger/$",
    #     schema_view.with_ui("swagger", cache_timeout=0),
    #     name="schema-swagger-ui",
    # ),
    # re_path(
    #     r"^redoc/$",
    #     schema_view.with_ui("redoc", cache_timeout=0),
    #     name="schema-redoc"
    # ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kite_expert/kites/urls.py
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy
from django.views.decorators.cache import cache_page

from kites import views

urlpatterns = [
    path("", cache_page(60)(views.Index.as_view()), name="home"),
    path("brand/<slug:slug>/", cache_page(60)(views.Brand.as_view()), name="brand"),
    path("expert/<slug:slug>/", cache_page(60)(views.Expert.as_view()), name="expert"),
    path("expert/", cache_page(60)(views.Expert.as_view()), name="experts"),
    path("kite/add/", views.KiteAdd.as_view(), name="kiteadd"),
    path("kite/edit/<int:pk>/", views.KiteEdit.as_view(), name="kitedit"),
    path("kite/del/<int:id>", views.kite_del, name="kitedel"),
    path("kite/<slug:slug>/", cache_page(60)(views.Kite.as_view()), name="kite"),
    path("register/<tk>/", views.UserRegister.as_view(), name="register"),
    path("register/", views.UserRegTest.as_view(), name="regtest"),
    path("login/", views.UserLogin.as_view(), name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("profile/edit/", views.UserProfileEdit.as_view(), name="profiledit"),
    path("profile/", views.UserProfile.as_view(), name="profile"),
    path("password/edit/", views.UserPasswordChange.as_view(), name="password_change"),
    path(
        "password/reset/done/",
        PasswordResetDoneView.as_view(
            template_name="overrides/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password/reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="kites/form_cycle_for.html",
            success_url=reverse_lazy("kites:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="overrides/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password/reset/",
        PasswordResetView.as_view(
            template_name="kites/form_cycle_for.html",
            email_template_name="overrides/password_reset_email.html",
            subject_template_name="overrides/password_reset_subject.txt",
            success_url=reverse_lazy("kites:password_reset_done"),
        ),
        name="password_reset",
    ),
]

kite_expert/kites/models.py
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Expert(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    about = models.TextField(blank=True)
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    # slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self) -> str:
        return self.user.username

    def get_absolute_url(self):
        return reverse("kites:expert", kwargs={"slug": self.user})

    class Meta:
        ordering = [
            "time_create",
        ]


class Kite(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True, verbose_name="URL")
    text = models.TextField(blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)
    brand = models.ForeignKey("Brand", on_delete=models.PROTECT)
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    photo1 = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)
    photo2 = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)
    photo3 = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)
    photo4 = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("kites:kite", kwargs={"slug": self.slug})

    def get_kiteedit_url(self):
        return reverse("kites:kitedit", kwargs={"pk": self.pk})

    def get_kitedel_url(self):
        return reverse("kites:kitedel", kwargs={"id": self.pk})

    def get_user_url(self):
        return reverse("kites:expert", kwargs={"slug": self.user})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        ordering = [
            "name",
        ]


class Brand(models.Model):
    name = models.CharField(max_length=50, unique=True, db_index=True)
    slug = models.SlugField(
        max_length=255, unique=True, db_index=True, verbose_name="URL"
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("kites:brand", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        ordering = [
            "name",
        ]

kite_expert/kites/views.py
from django.contrib.auth import logout  # login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.core.cache import cache
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, FormView, ListView, UpdateView

from kite_expert.settings import PROFILE_IMAGE, USER_IS_ACTIVE
from kites import forms, models, utils

from .tasks import resize_photo_expert, resize_photo_kite


class Index(utils.DataMixin, ListView):
    template_name = "kites/index.html"
    title_page = "All kites"

    def get_queryset(self):
        return (
            models.Kite.objects.values("name", "slug")
            .filter(is_published=True)
            .distinct()
        )


class Brand(utils.DataMixin, ListView):
    template_name = "kites/index.html"
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(title=context["object_list"][0]["brand__name"])
        return context

    def get_queryset(self):  # -> ValuesQuerySet[Kite, dict[str, Any]]
        slug = self.kwargs["slug"]
        return (
            models.Kite.objects.values("name", "brand__name", "slug")
            .filter(brand__slug=slug, is_published=True)
            .distinct()
        )


class Kite(utils.DataMixin, ListView):
    template_name = "kites/kite.html"
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            title=context["object_list"][0].name,
            brand=context["object_list"][0].brand.name,
        )
        return context

    def get_queryset(self):  # -> QuerySet[Kite]
        return (
            models.Kite.objects.filter(slug=self.kwargs["slug"], is_published=True)
            .order_by("time_create")
            .select_related("user")
        )


class KiteAdd(LoginRequiredMixin, utils.DataMixin, CreateView):
    form_class = forms.KiteForm
    template_name = "kites/form_cycle_for.html"
    title_page = "Add kite"

    def form_valid(self, form):
        form.instance.user = self.request.user
        kite = form.save()
        resize_photo_kite.delay(kite.pk)
        cache.clear()
        return super().form_valid(form)
        # auto redirect to get_absolute_url in models.Kite
        # return redirect(reverse_lazy('kites:kite', kwargs={'slug': form.instance.slug}))


class KiteEdit(LoginRequiredMixin, UserPassesTestMixin, utils.DataMixin, UpdateView):
    model = models.Kite
    form_class = forms.KiteForm
    template_name = "kites/form_cycle_for.html"
    title_page = "Edit kite"
    raise_exception = True

    def test_func(self):
        return self.request.user.id == self.get_object().user_id

    def get_success_url(self):
        # cache.clear()  # если не ипользуется метод form_valid (без celery)
        if self.object.is_published:
            return reverse_lazy("kites:kite", kwargs={"slug": self.object.slug})
        return reverse_lazy("kites:profile") + "#" + self.object.slug

    def form_valid(self, form):
        kite = form.save()
        resize_photo_kite.delay(kite.pk)
        cache.clear()
        return super().form_valid(form)


@login_required
def kite_del(request, id):
    kite = models.Kite.objects.get(pk=id)
    if request.user.id == kite.user_id:
        kite.delete()
        cache.clear()
    return redirect("kites:home")
    # return redirect(request.GET.get('next', 'kites:home'))


class Expert(utils.DataMixin, ListView):
    template_name = "kites/expert.html"
    title_page = "Experts"
    extra_context = {"profile_image": PROFILE_IMAGE}

    def get_queryset(self):
        if self.kwargs.get("slug"):
            return models.Expert.objects.filter(user__username=self.kwargs["slug"])
        return models.Expert.objects.all().select_related("user")


class UserRegTest(utils.DataMixin, FormView):
    form_class = forms.UserRegTestForm
    template_name = "kites/form_cycle_for.html"
    title_page = "Register Test"
    extra_context = {"comment": "Заполни форму кириллицей"}

    def form_valid(self, form):
        return redirect("kites:register", tk=utils.get_token())


class UserRegister(UserPassesTestMixin, utils.DataMixin, CreateView):
    form_class = forms.UserRegisterForm
    template_name = "kites/form_cycle_for.html"
    success_url = reverse_lazy("kites:login")
    title_page = "Register"
    raise_exception = True

    def test_func(self):
        return self.kwargs["tk"] == utils.get_token()

    def handle_no_permission(self):
        return redirect("kites:regtest")

    def form_valid(self, form):
        "метод вызывается при успешной отправке формы"
        if USER_IS_ACTIVE:
            user = form.save()
            # login(self.request, user) # автологин
        else:  # деактивация пользователя
            form.instance.is_active = False
            user = form.save()
        models.Expert.objects.create(user=user)  # создание эксперта для юзера
        return super().form_valid(form)


class UserLogin(utils.DataMixin, LoginView):
    form_class = forms.UserLoginForm
    template_name = "kites/form_cycle_for.html"
    title_page = "Login"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        href = reverse_lazy("kites:password_reset")
        context.update(bottom=f'<br><a href="{href}">I forgot my password</a>')
        return context

    def get_success_url(self):
        cache.clear()
        return reverse_lazy("kites:profile")


class UserProfile(LoginRequiredMixin, utils.DataMixin, DetailView):
    # model = models.Expert  # замена на queryset
    queryset = models.Expert.objects.select_related("user")
    template_name = "kites/profile.html"
    title_page = "Profile"
    extra_context = {"profile_image": PROFILE_IMAGE}

    def get_object(self):
        return models.Expert.objects.get(user=self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            user_kites=models.Kite.objects.filter(user=self.request.user.id)
            .order_by("is_published", "brand")
            .select_related("brand")
        )
        return context


class UserProfileEdit(LoginRequiredMixin, utils.DataMixin, UpdateView):
    model = models.Expert
    form_class = forms.ExpertForm
    template_name = "kites/form_cycle_for.html"
    slug_field = "user__username"
    title_page = "Edit profile"

    def get_object(self):
        return models.Expert.objects.get(user=self.request.user.pk)

    def get_success_url(self):
        return reverse_lazy("kites:profile")

    def form_valid(self, form):
        expert = form.save()
        resize_photo_expert.delay(expert.pk)
        return super().form_valid(form)


class UserPasswordChange(LoginRequiredMixin, utils.DataMixin, PasswordChangeView):
    form_class = forms.UserPasswordChangeForm
    success_url = reverse_lazy("kites:profile")
    template_name = "kites/form_cycle_for.html"
    title_page = "Password change"


def user_logout(request):
    logout(request)
    cache.clear()
    return redirect("kites:home")

kite_expert/kites/templates/kites/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'kites/css/styles.css' %}" type="text/css">
    <link rel="shortcut icon" href="{% static 'kites/images/icon.ico' %}" type="image/x-icon">
    <title>{{ title }}</title>
</head>

<body>
    <div class="head">
        <div class="head__left">
            <p>
                <a href="{% url 'kites:home' %}">Kites</a> | 
                <a href="{% url 'kites:experts' %}">Experts</a>
            </p>
        </div>
        <div class="head__right">
            {% if user.is_authenticated %}
            <p>
                    <a href="{% url 'kites:logout' %}">Logout</a>
                </p>
                {% else %}
                <p>
                    <a href="{% url 'kites:regtest' %}">Register</a> | 
                    <a href="{% url 'kites:login' %}">Login</a>
                </p>
                {% endif %}
        </div>
        <div class="head__user">
            {% if user.is_authenticated %}
            <p>
                <a href="{% url 'kites:kiteadd' %}">Add kite</a> | 
                <a href="{% url 'kites:profile' %}">{{ user }}</a>
            </p>
            {% endif %}
        </div>
    </div>
    <div class="main">
        <div class="sidenav">
            <div class="sidenav__details">
                <p>
                    <details>
                        <summary>Brands</summary>
                        {% include "kites/sidemenu.html" %}
                    </details>
                </p>
            </div>
            <div class="sidenav__not_details">
                <h1>Brands</h1>
                {% include "kites/sidemenu.html" %}
            </div>
        </div>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
    <!-- <div class="bottom"></div> -->
</body>
</html>


<!-- 
    {% if brand_selected == 0 %}
    <li>All</li>
    {% else %}
    {% endif %}
{% if i.pk == brand_selected %}
<li>{{ i.name }}</li>
{% else %}
{% endif %} 
-->

kite_expert/kites/templates/kites/blockimage.html
<p>
    {% if i.photo1 %}
    <div class="img-block">
        <a href="{{ i.photo1.url }}" title="open">
            <img class="img-kite" src="{{ i.photo1.url }}" alt="Kite_img_1">
        </a>
    </div>
    {% endif %}
    {% if i.photo2 %}
    <div class="img-block">
        <a href="{{ i.photo2.url }}" title="open">
            <img class="img-kite" src="{{ i.photo2.url }}" alt="Kite_img_2">
        </a>
    </div>
    {% endif %}
    {% if i.photo3 %}
    <div class="img-block">
        <a href="{{ i.photo3.url }}" title="open">
            <img class="img-kite" src="{{ i.photo3.url }}" alt="Kite_img_3">
        </a>
    </div>
    {% endif %}
    {% if i.photo4 %}
    <div class="img-block">
        <a href="{{ i.photo4.url }}" title="open">
            <img class="img-kite" src="{{ i.photo4.url }}" alt="Kite_img_4">
        </a>
    </div>
    {% endif %}
</p>

kite_expert/kites/templates/kites/expert.html
{% extends 'kites/base.html' %}
{% load static %}

{% block content %}
<h1>{{ title }}</h1>

{% for i in object_list %}

<p class="btn">{{ i.user }}</p>

<p>
    {% if i.photo %}
    <div class="img-block">
        <a href="{{ i.photo.url }}">
            <img class="img-kite" src="{{ i.photo.url }}" alt="Expert photo">
        </a>
    </div>
    {% else %}
    <div class="img-block">
        <img class="img-kite" src="{% static profile_image %}" alt="Expert photo">
    </div>
    {% endif %}
</p>

<p>{{ i.about | linebreaks | truncatechars_html:500 }}</p>

{% if not forloop.last %}
<hr>
{% endif %}

{% endfor %}

{% endblock %}

kite_expert/kites/templates/kites/form_cycle_for.html
{% extends 'kites/base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<h3>{{ comment }}</h3>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for f in form %}
    <div class="form-field">
        <div class="form-label">{{ f.label }}: </div>
        <div>{{ f }}</div>
    </div>
    {{ f.errors }}
    {% endfor %}
    <br>
    <!-- {% if form.instance.photo %}<img src="{{form.instance.photo.url}}" width="70">{% endif %} -->
    <p><button type="submit">Submit</button></p>
</form>

{{ bottom | safe}}

{% endblock %}

kite_expert/kites/templates/kites/index.html
{% extends 'kites/base.html' %}

{% block content %}
<h1>{{ title }}</h1>

{% for i in object_list %}

<p><a href="{% url 'kites:kite' i.slug %}" class="btn">{{ i.name|truncatechars:"20" }}</a></p>

{% endfor %}
<br>
<nav>
    {% if page_obj.has_other_pages %}
    {% for page in paginator.page_range %}
    {% if page_obj.number == page %}
    <p class="page current-page">{{ page }}</p>
    {% else %}
    <a href="?page={{ page }}" class="page">{{ page }}</a>
    {% endif %}
    {% endfor %}
    {% endif %}
</nav>

{% endblock %}

kite_expert/kites/templates/kites/kite.html
{% extends 'kites/base.html' %}

{% block content %}
<h1>{{ brand }}</h1>
<h1>{{ title }}</h1>

{% for i in object_list %}
<p><a class="btn" href="{{ i.get_user_url }}">{{ i.user }}</a></p>
<p>{{ i.text|linebreaks }}</p>

{% include "kites/blockimage.html" %}

{% if i.user == user %}
<p><a href="{{ i.get_kiteedit_url }}">Edit</a></p>
<p><a href="{{ i.get_kitedel_url }}?next={{ request.path|urlencode }}" 
    onClick="return window.confirm('Confirm?');">Delete</a></p>
{% endif %}

<p>last update: {{ i.time_update|date:'Y-m-d' }}</p>

{% if not forloop.last %}
<hr>
{% endif %}

{% endfor %}

{% endblock %}

kite_expert/kites/templates/kites/profile.html
{% extends 'kites/base.html' %}
{% load static %}

{% block content %}
<h1>{{ title }}</h1>
<p>
    {% if object.photo %}
    <div class="img-block">
        <a href="{{ object.photo.url }}" title="open">
            <img class="img-kite" src="{{ object.photo.url }}" alt="Expert photo">
        </a>
    </div>
    {% else %}
    <div class="img-block">
        <img class="img-kite" src="{% static profile_image %}" alt="Expert photo">
    </div>
    {% endif %}
</p>
<p>{{ object.about | linebreaks }}</p>
<p><a href="{% url 'kites:profiledit' %}">Edit profile</a></p>
<p><a href="{% url 'kites:password_change' %}">Edit password</a></p>

<h1>Posts:</h1>

{% for i in user_kites %}

<div id="{{ i.slug }}" class="anchor"></div>

{% if not i.is_published %}
<h3 class="btn">Not published!</h3>
{% endif %}

<h3>{{ i.brand }} | {{ i.name }}</h3>
<p>{{ i.time_create | date:'Y-m-d' }} | {{ i.time_update | date:'Y-m-d' }}</p>
<p>{{ i.text | linebreaks }}</p>

<details>
    <summary>Images</summary>
    
    {% include "kites/blockimage.html" %}
</details>

<p>
    <a href="{{ i.get_kiteedit_url }}">Edit</a> | 
    <a href="{{ i.get_kitedel_url }}?next={{ request.path | urlencode }}" 
    onClick="return window.confirm('Confirm?');">Delete</a>
</p>

{% if not forloop.last %}
<hr>
{% endif %}

{% endfor %}

{% endblock %}

kite_expert/kites/templates/kites/sidemenu.html
<ul>
    <li>
        <a href="{% url 'kites:home' %}">ALL</a>
    </li>
    {% for i in brands %}
    {% if i.kite__count > 0 %}
    <li>
        <a href="{{ i.get_absolute_url }}">{{ i.name }}</a>
    </li>
    {% endif %}
    {% endfor %}
</ul>